export default {
    PLATFORM_EVENT_SUBSCRIPTION_REQUEST: 'PLATFORM_EVENT_SUBSCRIPTION_REQUEST',
    PLATFORM_EVENT_SUBSCRIPTION_SUCCESS: 'PLATFORM_EVENT_SUBSCRIPTION_SUCCESS',
    PLATFORM_EVENT_SUBSCRIPTION_FAILURE: 'PLATFORM_EVENT_SUBSCRIPTION_FAILURE',
    PLATFORM_EVENT_UNSUBSCRIPTION_REQUEST: 'PLATFORM_EVENT_UNSUBSCRIPTION_REQUEST',
    PLATFORM_EVENT_UNSUBSCRIPTION_SUCCESS: 'PLATFORM_EVENT_UNSUBSCRIPTION_SUCCESS',
    PLATFORM_EVENT_UNSUBSCRIPTION_FAILURE: 'PLATFORM_EVENT_UNSUBSCRIPTION_FAILURE',
    DATA_CENTER_NAME_EVENT: 'DATA_CENTER_NAME_EVENT',
    DATA_CENTER_STATUS_EVENT: 'DATA_CENTER_STATUS_EVENT'
}