module.exports = {
    PLATFORM_EVENT_SUBSCRIPTION_REQUEST: 'PLATFORM_EVENT_SUBSCRIPTION_REQUEST',
    PLATFORM_EVENT_SUBSCRIPTION_SUCCESS: 'PLATFORM_EVENT_SUBSCRIPTION_SUCCESS',
    PLATFORM_EVENT_SUBSCRIPTION_FAILURE: 'PLATFORM_EVENT_SUBSCRIPTION_FAILURE',
    PLATFORM_EVENT_UNSUBSCRIPTION_REQUEST: 'PLATFORM_EVENT_UNSUBSCRIPTION_REQUEST',
    PLATFORM_EVENT_UNSUBSCRIPTION_SUCCESS: 'PLATFORM_EVENT_UNSUBSCRIPTION_SUCCESS',
    PLATFORM_EVENT_UNSUBSCRIPTION_FAILURE: 'PLATFORM_EVENT_UNSUBSCRIPTION_FAILURE'
}