module.exports = {
	PLATFORM_EVENT: 'PLATFORM_EVENT',
	PLATFORM_EVENT_SUBSCRIPTION_REQUEST: 'PLATFORM_EVENT_SUBSCRIPTION_REQUEST',
	PLATFORM_EVENT_SUBSCRIPTION_SUCCESS: 'PLATFORM_EVENT_SUBSCRIPTION_SUCCESS',
	PLATFORM_EVENT_SUBSCRIPTION_FAILURE: 'PLATFORM_EVENT_SUBSCRIPTION_FAILURE',
	PLATFORM_EVENT_UNSUBSCRIPTION_REQUEST: 'PLATFORM_EVENT_UNSUBSCRIPTION_REQUEST',
	PLATFORM_EVENT_UNSUBSCRIPTION_SUCCESS: 'PLATFORM_EVENT_UNSUBSCRIPTION_SUCCESS',
	PLATFORM_EVENT_UNSUBSCRIPTION_FAILURE: 'PLATFORM_EVENT_UNSUBSCRIPTION_FAILURE',
	SALESFORCE_LOGIN_SUCCESS: 'SALESFORCE_LOGIN_SUCCESS',
	SALESFORCE_LOGIN_FAILURE: 'SALESFORCE_LOGIN_FAILURE',
	COMETD_HANDSHAKE_SUCCESS: 'COMETD_HANDSHAKE_SUCCESS',
	COMETD_HANDSHAKE_FAILURE: 'COMETD_HANDSHAKE_FAILURE'
};